# Generated by Django 2.1.5 on 2023-12-29 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="creted_date",
            new_name="created_date",
        ),
    ]
